export const HERO_SUGGESTIONS: string[] = [
  "We rely on referrals",
  "We are a consultancy firm",
  "We stock in bulk and resell",
  "We develop software solutions based on client requirements",
  "We provide 24/7 personalised support",
  "We offer white-glove delivery and installation",
  "We provide on-site technical training",
  "We act as an outsourced department",
  "We offer emergency rapid-response times",
  "We provide bespoke tailoring for specialised equipment",
  "We facilitate networking and industry connections",
  "We offer concierge-level project management",
  "We manufacture in small batches for high quality",
  "We source exclusively from local producers",
  "We provide try-before-you-buy sample programs",
  "We offer subscription-based inventory replenishment",
  "We curate best-in-class product bundles",
  "We use 100% eco-friendly and compostable packaging",
  "We offer lifetime warranties on all craftsmanship",
  "We refurbish and resell high-end electronics",
  "We provide white-label manufacturing for other brands",
  "We provide API integrations between disparate systems",
  "We offer rapid prototyping and 3D modelling",
  "We provide creative direction and brand strategy",
  "We perform deep-dive technical security audits",
  "We offer fractional C-suite leadership talent",
  "We specialise in legacy system maintenance and repair",
  "We provide interactive data visualisation and analytics",
  "We offer UX/UI optimisation for digital platforms",
  "We conduct hyper-local market research",
  "We operate a low-overhead model to reduce client costs",
  "We offer flexible pay-as-you-grow payment plans",
  "We have no minimum order quantities",
  "We offer geographic exclusivity to our partners",
  "We provide turnkey solutions for retail franchises",
  "We leverage family-owned heritage and stability",
  "We offer risk-free performance-based trials",
  "We pivot service offerings based on real-time trends",
  "We provide navigation through complex regulatory red tape",
  "We offer unbundled services to prevent overpaying",
  "We specialise in sourcing hard-to-find or obsolete parts",
  "We provide linguistic and cultural localisation",
  "We cater to high-net-worth individuals requiring privacy",
  "We operate as an artisan workshop for handmade goods",
  "We provide 24-hour disaster recovery services",
  "We offer pop-up retail and temporary storefront solutions",
  "We focus on inclusive and accessible design standards",
  "We provide just-in-time inventory management",
  "We offer exclusive community membership access",
  "We provide radical transparency in the supply chain",
];
